[package]
name = "ark_compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.14", features = ["derive"] }
colored = "2.1.0"
enum-map = "2.7.3"
fancy-regex = "0.13.0"
regex = "1.10.2"
